// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakyJgj5xiBYl8c_Le04sLtwwROJKg0NA',
    appId: '1:719528473790:web:614ebb02dcbc7a0ac7daef',
    messagingSenderId: '719528473790',
    projectId: 'aptechproject-10e42',
    authDomain: 'aptechproject-10e42.firebaseapp.com',
    storageBucket: 'aptechproject-10e42.firebasestorage.app',
    measurementId: 'G-Z8JV5F0GK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyttOjI71-UYVjoz9CYi8_dEeaKHmVgXg',
    appId: '1:719528473790:android:d74ace56969281ffc7daef',
    messagingSenderId: '719528473790',
    projectId: 'aptechproject-10e42',
    storageBucket: 'aptechproject-10e42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_qj2qIiwS1jBsUImFyWmtax6Fh50hkyA',
    appId: '1:719528473790:ios:0331b76a84abaf20c7daef',
    messagingSenderId: '719528473790',
    projectId: 'aptechproject-10e42',
    storageBucket: 'aptechproject-10e42.firebasestorage.app',
    iosBundleId: 'com.example.aptechProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_qj2qIiwS1jBsUImFyWmtax6Fh50hkyA',
    appId: '1:719528473790:ios:0331b76a84abaf20c7daef',
    messagingSenderId: '719528473790',
    projectId: 'aptechproject-10e42',
    storageBucket: 'aptechproject-10e42.firebasestorage.app',
    iosBundleId: 'com.example.aptechProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakyJgj5xiBYl8c_Le04sLtwwROJKg0NA',
    appId: '1:719528473790:web:29a2132649a4bbb5c7daef',
    messagingSenderId: '719528473790',
    projectId: 'aptechproject-10e42',
    authDomain: 'aptechproject-10e42.firebaseapp.com',
    storageBucket: 'aptechproject-10e42.firebasestorage.app',
    measurementId: 'G-F5DL6RHF5N',
  );
}
